# Generated by Django 5.1.4 on 2024-12-21 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.AutoField(primary_key=True, serialize=False)),
                ('EventType', models.CharField(max_length=50)),
                ('EventTitle', models.CharField(max_length=70)),
                ('EventDescription', models.TextField()),
                ('EventDate', models.DateField()),
                ('EventTime', models.TimeField()),
                ('EventCost', models.CharField(default='Free', max_length=20)),
                ('EventLocation', models.CharField(max_length=70)),
                ('EventCapacity', models.PositiveIntegerField(blank=True, null=True)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('form_configured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('email', 'Email'), ('number', 'Number'), ('select', 'Dropdown'), ('date', 'Date'), ('time', 'Time')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices for dropdown', null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='User_app.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('cash', 'Cash')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('not_required', 'Not Required')], default='not_required', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_app.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
    ]
